steps:
  # Step 1: Clone the GitHub repository
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone https://github.com/th3-v3ng34nc3/AccuKnox-IaC-Scan-GCP.git /workspace/AccuKnox_Iac

  # Step 2: Install Checkov and run the scan, saving the report in JSON format
  - name: 'python:3.8'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install checkov && \
        checkov -d /workspace/AccuKnox_Iac --output json > /workspace/checkov_report.json || true

  # Step 3: Access the secret using gcloud and save it to a file
  - name: 'gcr.io/cloud-builders/bash'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=accuknox_token --format='get(payload.data)' | tr '_-' '/+' | base64 -d > /workspace/decrypted-data.txt

  # Step 7: Push report to CSPM panel
  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl --location --request POST "https://${_CSPM_URL}/api/v1/artifact/?tenant_id=${_TENANT_ID}&data_type=IAC&save_to_s3=false" \
          --header "Tenant-Id: ${_TENANT_ID}" \
          --header "Authorization: Bearer $(cat /workspace/decrypted-data.txt)" \
          --form "file=@/workspace/checkov_report.json"
# Step 4: Store the Checkov report as an artifact
artifacts:
  objects:
    location: 'gs://aditya-cicd-test/checkov-reports/'
    paths: 
      - 'checkov_report.json'
# Define substitutions
substitutions:
  _IMAGE_URL: 'gcr.io/shaped-infusion-402417/python-app'
  _IMAGE_TAG: 'latest'
  _CSPM_URL: 'cspm.demo.accuknox.com'
  _TENANT_ID: '167'
  _BUCKET_NAME: 'gs://aditya-cicd-test'

# Define timeout for the entire pipeline
timeout: '1200s' # 20 minutes

logsBucket: 'gs://aditya-cicd-test'
